"""empty message

Revision ID: 711d989b35d9
Revises: 7f8d0b55371b
Create Date: 2024-05-30 16:15:38.883773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '711d989b35d9'
down_revision = '7f8d0b55371b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.String(length=50), nullable=False))
        batch_op.drop_index('name')
        batch_op.create_unique_constraint(None, ['role_name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.drop_column('role_name')

    # ### end Alembic commands ###
